{% set name = "nlptest" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
    fn: nlptest-1.0.2.tar.gz
    url: https://files.pythonhosted.org/packages/e0/e3/500e7c45404f52dae3858819b7d7c1d8cd8086624993616953ad922f86f3/nlptest-1.0.1.tar.gz
    sha256: 4d56528a2af3bbc335a98f81b105e21d8cfada220939efbe2d43ac8abae26b7a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7,<3.12
  run:
    - python >=3.7,<3.12
    - numpy
    - pandas
    - scikit-learn
    - transformers
    - pytorch
    - sentencepiece
    - pydantic

about:
  home: https://github.com/JohnSnowLabs/nlptest/
  license: Apache License 2.0
  license_family: APACHE
  license_url: https://github.com/JohnSnowLabs/nlptest/blob/main/LICENSE
  description: John Snow Labs' NLP Test is a Python library for testing NLP models and datasets. It comes with over 50 tests covering fairness, robustness, accuracy, bias and representation for named entity recognition and text classification.
  summary: Deliver safe & effective NLP models in a few lines of code.
