lang:
- en
- du
- it
tasks:
- ner
- text_classifer
tests_types:
- uppercase
- lowercase
- add_context:
  - starting_context:
    - Hello
    - 'Dated: 21/02/2022'
  - ending_context:
    - Bye
    - Reported
